-- CA Par Annee et par mois
WITH RawData AS (
SELECT  YEAR(DATE_COMMANDE) AS Annee, 
		MONTH(DATE_COMMANDE) AS Mois,
		SUM(CA) AS CA
FROM ResumeCA
GROUP BY YEAR(DATE_COMMANDE), MONTH(DATE_COMMANDE)

)
SELECT *,
	SUM(CA) OVER (PARTITION BY ANNEE ORDER BY Annee, Mois ROWS BETWEEN UNBOUNDED PRECEDING 
													AND CURRENT ROW) AS CummulAN,
	CA-(AVG(CA) OVER (ORDER BY Annee, Mois ROWS BETWEEN 3 PRECEDING 
													AND 1 PRECEDING)) AS MOY3MOISPREC,
	CA-LAG(CA,12) OVER  (ORDER BY Annee, Mois) AS MemeMoisANPrec,
		CA-LEAD(CA,12) OVER  (ORDER BY Annee, Mois) AS MemeMoisANSuivant
FROM RawData
ORDER BY Annee,Mois