SELECT 
	CODE_CATEGORIE, NO_FOURNISSEUR , -- Critères de regroupement
	COUNT(*)							-- Aggregation sur les autres colonnes
FROM PRODUITS 
GROUP BY CODE_CATEGORIE, NO_FOURNISSEUR  -- Critères de regroupement

SELECT *
FROM PRODUITS 
ORDER BY CODE_CATEGORIE, NO_FOURNISSEUR


SELECT COUNT(*) 
FROM PRODUITS
WHERE CODE_CATEGORIE=1