-- Tous les CodeClients qui ont achete le produit 45
WITH Cli45 AS (
SELECT DISTINCT  CODE_CLIENT 
FROM Commandes AS C
INNER JOIN DETAILS_COMMANDES AS DC ON DC.NO_COMMANDE=C.NO_COMMANDE
WHERE REF_PRODUIT=45 AND QUANTITE>0),
Cli46 AS (
SELECT DISTINCT  CODE_CLIENT 
FROM Commandes AS C
INNER JOIN DETAILS_COMMANDES AS DC ON DC.NO_COMMANDE=C.NO_COMMANDE
WHERE REF_PRODUIT=46 AND QUANTITE>0
)
SELECT * FROM Clients
WHERE CODE_CLIENT IN(SELECT CODE_CLIENT FROM Cli45 EXCEPT SELECT CODE_CLIENT FROM Cli46)