SELECT REF_PRODUIT AS 'REF_PRODUIT',
		SUM(Quantite) AS 'Quantity',
		SUM(Quantite*Prix_Unitaire) AS 'CA'
		
FROM DETAILS_COMMANDES
WHERE Remise=0
GROUP BY REF_PRODUIT
HAVING SUM(Quantite) >=500
ORDER BY CA DESC